sudo: required
services:
  - docker

 before_install:
  - docker build -t MounirChennana/docker-react -f Dockerfile.dev .

script:
  - docker run MounirChennana/docker-react npm run test -- --coverage